amboro_store/urls.py
"""amboro_store URL Configuration
"""
from django.contrib import admin

from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView
urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar',views.remove,name='remove')
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('pago', views.payment, name='payment'),
    path('completados', views.OrderListView.as_view(), name='completeds')



]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'

urlpatterns=[
    path('search', views.ProductSearchListView.as_view(),name="search"),
    path('<slug:slug>', views.ProductDetailView.as_view(),name='product'),#id primary key
]

carts/models.py
import uuid
import decimal

from django.db import models
from orders.common import OrderStatus
from users.models import User
from products.models import Product
from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed


class Cart(models.Model):
    cart_id = models.CharField(max_length=100,null=False, blank=False, unique=True )
    user = models.ForeignKey(User, null=True,blank=True, on_delete=models.CASCADE)#uno a muchos entre carrito con usuarios
    products = models.ManyToManyField(Product, through='CartProducts')#muchos a muchos entre carrito y productos
    subtotal = models.DecimalField(default=0.0,max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add = True)
    FEE = 0.05 #importe del 0.05%

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total

    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
         ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE) )
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')

    def has_products(self):
        return self.products.exists()

    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

carts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .models import CartProducts
from products.models import Product
from .utils import get_or_create_cart

def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    # cart.products.add(product, through_defaults={
    #     'quantity': quantity
    # })
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart,
                                                                    product=product,
                                                                    quantity=quantity)

    return render(request, 'carts/add.html', {
        'quantity': quantity,
        'cart_product': cart_product,
        'product': product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('carts:cart')

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load cart_extras %}
{% block content %}

<div class="col-3">
  {% if product.image %}
    <img src="{{ product.image.url }}" alt="Imagen del Producto"width="200"height="200">
  {% endif %}
</div>

<div class="col">
  <div class="h3 font-weight-bold text-success">
    {{ quantity | quantity_add_format }} al carrito
  </div>
  <div class="">
    <a href="{% url 'products:product' product.slug %}">
      {{ product.tittle }}
    </a>
  </div>
  <div class="font-weight-bold text-danger">
    {{ product.price }}
  </div>
  <div class="mt-2">
    <a href="{% url 'carts:cart' %}" class="btn btn-info">Ver Carrito</a>
  </div>
  <div class="mt-2">
    <a href="{% url 'index' %}" class ="btn btn-info">Seguir Comprado</a>
  </div>
</div>
{% endblock %}

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load product_extras %}

{% block content %}
  {% if cart.products.exists %}
    <div class="col-8">
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio</th>
          </tr>
        </thead>
        <tbody>
          {% for cp in cart.products_related %}
            {% with product=cp.product %}
              <tr>
                <th>{{ forloop.counter }}</th>
                <th>
                  {% if product.image %}
                  <img src="{{ product.image.url }}" alt="Imagen del producto" width="60" height="60">
                  {% endif %}
                </th>
                <th>
                  <a href="{% url 'products:product' product.slug %}">{{product.tittle}}</a>
                  {%include 'carts/snippets/remove.html'%}
                </th>
                <th>{{cp.quantity}}</th>
                <th>
                  <span class='font-weight-bolt text-danger'>{{product.price | price_format }}</span>
                </th>
              </tr>
            {%endwith%}
          {%endfor%}
        </tbody>
      </table>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <div class="font-weight-bold">
            Subtotal({{ cart.products.count }}): <span class="text-danger">{{ cart.subtotal | price_format }}</span>
          </div>
          <div class="mt-2">
            <a href="{% url 'orders:order' %}" class="btn btn-warning">Proceder al pago</a>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="col">
      <p class="h3">Tu carrito de compras esta vacio.</p>
      <a href="{% url 'index' %}">Seguir Comprando</a>
    </div>
  {% endif %}

{% endblock %}