amboro_store/urls.py
"""amboro_store URL Configuration
"""
from django.contrib import admin

from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView
urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar',views.remove,name='remove')
]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'

urlpatterns=[
    path('search', views.ProductSearchListView.as_view(),name="search"),
    path('<slug:slug>', views.ProductDetailView.as_view(),name='product'),#id primary key
]

products/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

import uuid

class Product(models.Model):
    tittle =models.CharField(max_length=50)
    description=models.TextField()
    price=models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug=models.SlugField(null=False, blank=False, unique=True)
    image=models.ImageField(upload_to='products/',null=False, blank=False)
    created_at=models.DateTimeField(auto_now_add=True)


    #def save(self, *args, **kwargs):
    #    self.slug= slugify(self.tittle)
    #    super(Product,self).save(*args, **kwargs)


    def __str__(self):
        return self.tittle

def set_slug(sender,instance, *args, **kwargs):
    if instance.tittle and not instance.slug:
        slug = slugify(instance.tittle)

        while Product.objects.filter(slug=slug).exists():
            slug=slugify(
            '{}-{}'.format(instance.tittle,str(uuid.uuid4())[:8])
            )

        instance.slug=slug

pre_save.connect(set_slug, sender=Product)

products/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Product
from django.db.models import Q

# Create your views here.
class ProductListView(ListView):
    template_name='index.html'
    queryset=Product.objects.all().order_by('-id')
    #paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message']='Lista de Productos'
        return context
class ProductDetailView(DetailView):#id->PK
    model=Product
    template_name='products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print('/n')
        print(context)
        print('/n')
        return context

class ProductSearchListView(ListView):
    template_name='products/search.html'
    def get_queryset(self):
        filters = Q(tittle__icontains=self.query())|Q(category__tittle__icontains=self.query())
        return Product.objects.filter(filters)
    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query']=self.query()
        context['count']= context['product_list'].count()

        return context

products/templates/products/snippets/list.html
<div class="row">
  {%for object in product_list%}
    <div class="col-3 mt-5">

      {%include 'products/snippets/product.html' with product=object%}

    </div>
  {%endfor%}
</div>

products/templates/products/snippets/product.html
<div class="card h-100">
  {% if product.image %}
    <img src="{{ product.image.url }}" alt="Imagen del Producto" height="300" >
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{product.tittle}}</h5>      <!--card.title or tittle-->
    <p class="card-text">{{ product.description }}</p>

  </div>
  <a href="{% url 'products:product' product.slug %}"class="btn btn-primary">Ver mas</a>

</div>

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
      <input type="text" name="q" value="{{query}}" class="form-control"placeholder="Buscar">
      <div class="input-group-append">
        <input type="submit" name=""value="Buscar"class="btn btn-primary">
      </div>
    </div>
</form>