amboro_store/urls.py
"""amboro_store URL Configuration
"""
from django.contrib import admin

from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView
urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar',views.remove,name='remove')
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('pago', views.payment, name='payment'),
    path('completados', views.OrderListView.as_view(), name='completeds')



]

shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

orders/models.py
import uuid
from django.db import models

from .common import OrderStatus
from .common import choices
from billing_profiles.models import BillingProfile

from users.models import User
from carts.models import Cart
from shipping_addresses.models import ShippingAddress
from django.db.models.signals import pre_save



class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices,
                                                default=OrderStatus.CREATED) #Enum
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress,
                                        null=True, blank=True,
                                        on_delete=models.CASCADE)
    billing_profile = models.ForeignKey(BillingProfile, null=True, blank=True,
                                        on_delete=models.CASCADE)



    def __str__(self):
        return self.order_id

    def get_or_set_billing_profile(self):
        if self.billing_profile:
            return self.billing_profile

        billing_profile = self.user.billing_profile
        if billing_profile:
            self.update_billing_profile(billing_profile)

        return billing_profile

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address

        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)

        return shipping_address

    def update_billing_profile(self, billing_profile):
        self.billing_profile = billing_profile
        self.save()

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()


    def update_total(self):
        self.total = self.get_total()
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()

    def get_total(self):
        return self.cart.total + self.shipping_total

    @property
    def description(self):
        return 'Compra por ({}) producto(s) '.format(
            self.cart.products.count()
        )


def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
import threading
from charges.models import Charge
from django.db import transaction
from .utils import breadcrumb
from .utils import destroy_order
from carts.utils import destroy_cart
from carts.utils import get_or_create_cart
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .utils import get_or_create_order
from .models import Order
from .mails import Mail
from shipping_addresses.models import ShippingAddress

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet
from .decorators import validate_cart_and_order


# Create your views here.

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()
@validate_cart_and_order
@login_required(login_url='login')
def order(request, cart, order):

    if not cart.has_products():
        return redirect('carts:cart')

    return render(request, 'orders/order.html',{
        'cart': cart,
        'order': order,
        'breadcrumb':breadcrumb()
    })
@validate_cart_and_order
@login_required(login_url='login')
def address(request, cart, order):


    #shipping_address = order.shipping_address
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()

    return render(request, 'orders/address.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address,
        'can_choose_address': can_choose_address,
        'breadcrumb': breadcrumb(address=True)
    })

@login_required(login_url='login')
def select_address(request):

    shipping_addresses = request.user.addresses
    return render(request, 'orders/select_address.html', {
        'breadcrumb': breadcrumb(address=True),
        'shipping_addresses': shipping_addresses
    })

@login_required(login_url='login')
@validate_cart_and_order
def check_address(request, cart, order, pk):
    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)

    return redirect('orders:address')


@login_required(login_url='login')
@validate_cart_and_order
def payment(request, cart, order):
    if not cart.has_products() or order.shipping_address is None:
        return redirect('carts:cart')

    billing_profile = order.get_or_set_billing_profile()

    return render(request, 'orders/payment.html', {
        'cart': cart,
        'order': order,
        'billing_profile': billing_profile,
        'breadcrumb': breadcrumb(address=True, payment=True)
    })


@validate_cart_and_order
@login_required(login_url='login')
def confirm(request, cart, order):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if not cart.has_products() or order.shipping_address is None or order.billing_profile is None:
        return redirect('carts:cart')

    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address,
        'breadcrumb': breadcrumb(address=True, payment=True, confirmation=True)
    })
@validate_cart_and_order
@login_required(login_url='login')
def cancel(request, cart, order):

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()

    destroy_cart(request)
    destroy_order(request)

    messages.error(request, 'Orden cancelada')
    return redirect('index')

@validate_cart_and_order
@login_required(login_url='login')
def complete(request, cart, order):
    if request.user.id != order.user_id:
        return redirect('carts:cart')

    charge = Charge.objects.create_charge(order)
    if charge:
        with transaction.atomic():
            order.complete()

            thread = threading.Thread(target=Mail.send_complete_order, args=(
                order, request.user
            ))
            thread.start()

            destroy_cart(request)
            destroy_order(request)

            messages.success(request, 'Compra completada exitosamente')
    return redirect('index')

orders/templates/orders/address.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col">
    {% if shipping_address %}
      <div class="h3">
        Recoge el pedido en el punto de entrega
      </div>
      <div class="">
        {% include 'shipping_addresses/snippets/shipping_address.html' %}

        <div class="mt-2">
          <a href="{% url 'orders:payment' %}" class="btn btn-warning">Entregar a esta direccion</a>
        </div>

        {% if can_choose_address %}
          <div class="mt-2">
            <a href="{% url 'orders:select_address' %}">Otra dirección</a>
          </div>
        {% endif %}
      </div>
    {% else %}
      <div class="h3">
        Registra tu dirección de envío
      </div>
      <div class="">
        {% url 'orders:address' as next_url %}
        <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}">Nueva dirección de envío</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

orders/templates/orders/confirm.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col-8">
    <div class="h3">
      Confirma tu Pedido
    </div>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <div class="font-weight-bold">
              Direccion de Envio
            </div>
            <div class="cart-text">
              {{ shipping_address.address }}
            </div>
            <div class="cart-text">
              {{ shipping_address.line1 }}
            </div>
            <div class="cart-text">
              {{ shipping_address.reference }}
            </div>
            <div class="cart-text">
              {{ shipping_address.postal_code }}
            </div>
          </div>


          <div class="col-6">
            <div class="font-weight-bold">
              Metodo de Pago
            </div>
            <div class="cart-text">
              Tarjeta terminacion {{ order.billing_profile.last4 }}
            </div>
          </div>

<!--
          <div class="col-4">
            <div class="font-weight-bold">
              CodigoPromocional
            </div>
            <form>
              <input type="text" name="code" value="" class="form-control" placeholder="promo_code">
            </form>
          </div>
-->

        </div>
      </div>
    </div>
    <div class="mt-3">
      <div class="card">
        <div class="card-body">
          {% for product in cart.products.all %}
            {% include 'orders/snippets/product.html'%}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="col mt-3">
    <br>
    {% url 'orders:complete' as next_url %}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
    <div class="mt-2">
      <a href="{% url 'orders:cancel' %}"class="btn btn-danger">Cancelar Orden</a>
    </div>
  </div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col-8">
    <div class="h3">
      Revisa tu pedido
    </div>
    <div class="card">
      <div class="card-body">
        {% for product in cart.products.all %}
          {% include 'orders/snippets/product.html' %}
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col">
    {% url 'orders:address' as next_url%}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
  </div>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'base.html' %}

{% block content %}
  <div class="col">
    <div class="h3">
      Mis pedidos
    </div>
    <div class="">
      {% for order in object_list %}
        {% include 'orders/snippets/order.html' %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

orders/templates/orders/payment.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col">
    <div class="h3">
      Método de pago
    </div>
    <div class="">
      {% include 'billing_profiles/snippets/billing_profile.html' %}
    </div>
    <div class="mt-2">
      <a href="{% url 'orders:confirm' %}" class="btn btn-warning">Confirmar</a>
    </div>
  </div>
{% endblock %}

orders/templates/orders/select_address.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col">
    <div class="h3">
      Selecciona una dirección de envío
    </div>
    <div class="mt-2">
      {% for shipping_address in shipping_addresses %}
        <div class="card mb-2">
          <div class="card-body">
            <h5 class="card-title">{{ shipping_address.address }}</h5>
            <p class="card-title">{{ shipping_address.postal_code }}</p>
            <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">
              Seleccionar
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}