amboro_store/urls.py
"""amboro_store URL Configuration
"""
from django.contrib import admin

from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView
urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns = [
    path('', views.BillingProfileListView.as_view(), name='billing_profiles'),
    path('nuevo', views.create, name='create')
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar',views.remove,name='remove')
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('pago', views.payment, name='payment'),
    path('completados', views.OrderListView.as_view(), name='completeds')



]

shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if stripe_public_key %}
      <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}

    {% block css %}
    {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}

    <div class="container">

      {% include 'messages.html' %}

      {% block breadcrumb %}
      {% endblock %}

      <div class="row mt-3">

        {% block content %}
        {% endblock %}

      </div>
    </div>
    
  </body>
  <script src="https://kit.fontawesome.com/7efd9e34c5.js"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block javascript %}
  {% endblock %}

</html>

templates/index.html
  {%extends 'base.html' %}
  {%block content%}
  <div class="col">
    <h4 class="text-center">{{message}}</h4>

    {%include 'products/snippets/search.html'%}

    {% if is_paginated %}
      <div class="mt-2">

        <ul class="pagination pagination-lg">

          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}"class="page-link">Previous</a>
            </li>
          {% else %}

            <li class="page-item disabled">
              <a href="#"class="page-link">Previous</a>
            </li>

          {% endif %}

          {% for i in paginator.page_range %}


              <li class="page-item {% if page_obj.number == i %} active {% endif %}">
                <a href="?page={{ i }}"class="page-link">{{i}}</a>
              </li>

          {% endfor %}


          {% if page_obj.has_next %}
            <li class="page-item">
              <a href="?page={{ page_obj.next_page_number  }}"class="page-link">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a href="#"class="page-link">Next</a>
            </li>
          {% endif %}

        </ul>

      </div>
    {% endif %}
    {% include 'products/snippets/list.html'%}
    <footer class="mt-5">
           <div class="container my-auto">
             <div class="copyright text-center my-auto">
               <span>copyright &copy; <script> document.write(new Date().getFullYear()); </script> - developed by
                 <b><a href="https://indrijunanda.gitlab.io/" target="_blank">jquis812</a></b>
               </span>
             </div>
           </div>
    </footer>
  </div>
  {%endblock%}

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{% else %}alert-danger {% endif %}">
      <button type="button" class="close" data-dismiss"alert">x</button>
      {{message}}
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
  {% url 'login ' as login %}
  {% url 'register ' as register %}
  {% url 'carts:cart' as cart %}
  {% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
  {% url 'orders:completeds' as completeds %}
  {% url 'billing_profiles:billing_profiles' as billing_profiles %}

  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}"class="navbar-brand">Miel de Abeja Amboro</a>
    <button type="button" name="button"class="navbar-toggler navbar-toggler-right" data-toggle="collapse"data-target="#navb">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb"class="navbar-collapse collapse hide">
      <ul class='navbar-nav'>
        <li class= "nav-item {% if request.path == cart  %}active{%endif%}">
          <a class="nav-link" href="{{ cart }}">
            Carrito <span class="fas fa-shopping-cart"></span>
          </a>
        </li>

        {% if user.is_authenticated %}
          <li class= "nav-item {% if request.path == shipping_addresses  %}active{%endif%}">
            <a class="nav-link" href="{{ shipping_addresses }}">
              Mis Direcciones <span class="fas fa-location-arrow"></span>
            </a>
          </li>

          <li class= "nav-item {% if request.path == completeds  %}active{%endif%}">
            <a class="nav-link" href="{{ completeds }}">
              Mis pedidos <span class="fas fa-shipping-fast"></span>
            </a>
          </li>

          <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
            <a class="nav-link" href="{{ billing_profiles }}">
              Mis métodos de pago <span class="fab fa-cc-stripe"></span>
            </a>
          </li>

        {% endif %}



      </ul>
      <ul class="nav navbar-nav ml-auto">
        {%if user.is_authenticated%}
        <li class="navbar-item">
          <a href="{% url 'logout' %}"class="nav-link">
            <span class="fas fa-sign-in-alt"></span>
            Logout</a>
        </li>
        {%else%}
          <li class="navbar-item">
            <a href="{%url 'login'%}"class="nav-link">
              <span class="fas fa-user"></span>
              Login</a>
          </li>

          <li class="navbar-item">
            <a href="{% url 'register' %}"class="nav-link">
              <span class="fas fa-user-plus"></span>
              Registro</a>
          </li>


        {%endif%}
      </ul>
    </div>
  </nav>